# Generated by Django 4.1.4 on 2023-03-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_activity_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="actual_duration",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="activity",
            name="actual_finish",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="actual_start",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="free_float",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="activity",
            name="late_finish",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="late_start",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="original_duration",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="activity",
            name="remaining_duration",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="activity",
            name="total_float",
            field=models.IntegerField(default=0),
        ),
    ]
