# Generated by Django 4.1.4 on 2023-03-11 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0004_alter_activity_actual_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relation",
            name="predecessor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predecessors",
                to="scheduler.activity",
            ),
        ),
    ]
