# Generated by Django 4.1.4 on 2023-03-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0008_activity_critical"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="finish",
            field=models.DateField(null=True),
        ),
    ]
